# -*- coding: utf-8 -*-
"""Movie-Lens.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1em0rPmg7YMnWK56HTdIf_jmNgooWwwVb
"""

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from fastai.collab import *

import zipfile
with zipfile.ZipFile('/content/movielens-100k-dataset.zip') as f:
  f.extractall('/content')
path = Path('/content/ml-100k')
path.ls()

ratings = pd.read_csv(path/'u.data',delimiter='\t',header = None,names = ['user_id','movie_id','ratings','timestamp'])
ratings.head()

movies = pd.read_csv(path/'u.item',  delimiter='|', encoding='latin-1', header=None,names=['movie_id', 'title', 'date', 'N', 'url', *[f'g{i}' for i in range(19)]])
movies.head()

len(ratings)

len(movies)

movie_rating = ratings.merge(movies[['movie_id','title']])

movie_rating.head()

data = CollabDataBunch.from_df(movie_rating, seed=101, valid_pct=0.1, item_name='title')

data.show_batch()

y_range = [0,5.5]

learn = collab_learner(data, n_factors=50, y_range=y_range, wd=1e-1,metrics=mean_squared_error)

learn.lr_find()
learn.recorder.plot(skip_end=10)

learn.fit_one_cycle(6,1e-02,)

